create schema if not exists extensions;

create extension if not exists postgis
with schema extensions;

-- USER PROFILES

create table public.profiles (
    id uuid primary key
        references auth.users(id)
        on delete cascade,

    display_name varchar(100) not null,

    avatar_url text,

    preferred_language varchar(5)
        not null
        default 'th',

    account_status varchar(20)
        not null
        default 'active',

    reputation_score integer
        not null
        default 0,

    created_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now(),

    constraint profiles_language_check
        check (
            preferred_language in ('th', 'en')
        ),

    constraint profiles_account_status_check
        check (
            account_status in (
                'active',
                'suspended',
                'deleted'
            )
        ),

    constraint profiles_reputation_check
        check (reputation_score >= 0)
);

-- REPORT CATEGORIES

create table public.report_categories (
    id smallint
        generated by default as identity
        primary key,

    code varchar(50)
        not null
        unique,

    name_th varchar(100)
        not null,

    name_en varchar(100)
        not null,

    default_expiry_minutes integer,

    is_active boolean
        not null
        default true,

    created_at timestamptz
        not null
        default now(),

    constraint report_categories_expiry_check
        check (
            default_expiry_minutes is null
            or default_expiry_minutes > 0
        )
);

-- INCIDENT REPORTS

create table public.incident_reports (
    id uuid
        primary key
        default gen_random_uuid(),

    category_id smallint
        not null
        references public.report_categories(id),

    reported_by uuid
        not null
        references auth.users(id)
        on delete cascade,

    title varchar(200)
        not null,

    description text,

    -- พิกัด WGS84 ร่วมกับ Google Maps
    location extensions.geography(Point, 4326)
        not null,

    place_name varchar(255),

    severity varchar(20)
        not null
        default 'medium',

    status varchar(20)
        not null
        default 'pending',

    occurred_at timestamptz
        not null
        default now(),

    expires_at timestamptz,

    confidence_score numeric(6, 2)
        not null
        default 0,

    duplicate_of_report_id uuid
        references public.incident_reports(id)
        on delete set null,

    created_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now(),

    constraint incident_reports_title_check
        check (
            char_length(trim(title)) >= 3
        ),

    constraint incident_reports_severity_check
        check (
            severity in (
                'low',
                'medium',
                'high',
                'critical'
            )
        ),

    constraint incident_reports_status_check
        check (
            status in (
                'pending',
                'verified',
                'rejected',
                'resolved',
                'expired'
            )
        ),

    constraint incident_reports_confidence_check
        check (
            confidence_score >= 0
            and confidence_score <= 100
        ),

    constraint incident_reports_expiry_check
        check (
            expires_at is null
            or expires_at > created_at
        )
);

-- Index สำหรับค้นหาเหตุการณ์ใกล้ตำแหน่ง 

create index incident_reports_location_gix
on public.incident_reports
using gist (location);

create index incident_reports_status_created_idx
on public.incident_reports (
    status,
    created_at desc
);

create index incident_reports_category_idx
on public.incident_reports (category_id);

create index incident_reports_reported_by_idx
on public.incident_reports (reported_by);

-- REPORT VOTES

create table public.report_votes (
    report_id uuid
        not null
        references public.incident_reports(id)
        on delete cascade,

    user_id uuid
        not null
        references auth.users(id)
        on delete cascade,

    vote_type varchar(20)
        not null,

    created_at timestamptz
        not null
        default now(),

    primary key (report_id, user_id),

    constraint report_votes_type_check
        check (
            vote_type in (
                'confirm',
                'resolved',
                'false_report'
            )
        )
);

create index report_votes_user_idx
on public.report_votes (user_id);

-- SAVED ROUTES

create table public.saved_routes (
    id uuid
        primary key
        default gen_random_uuid(),

    user_id uuid
        not null
        references auth.users(id)
        on delete cascade,

    route_name varchar(150)
        not null,

    origin_place_id varchar(255),

    origin_name varchar(255)
        not null,

    origin_location extensions.geography(Point, 4326)
        not null,

    destination_place_id varchar(255),

    destination_name varchar(255)
        not null,

    destination_location extensions.geography(Point, 4326)
        not null,

    route_preference varchar(30)
        not null
        default 'fastest',

    created_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now(),

    last_used_at timestamptz,

    constraint saved_routes_name_check
        check (
            char_length(trim(route_name)) >= 1
        ),

    constraint saved_routes_preference_check
        check (
            route_preference in (
                'shortest_distance',
                'cheapest',
                'least_walking',
                'least_time'
            )
        )
);

create index saved_routes_user_created_idx
on public.saved_routes (
    user_id,
    created_at desc
);

create index saved_routes_origin_location_gix
on public.saved_routes
using gist (origin_location);

create index saved_routes_destination_location_gix
on public.saved_routes
using gist (destination_location);

-- FARE CHANGE REQUESTS

create table public.fare_change_requests (
    id uuid
        primary key
        default gen_random_uuid(),

    submitted_by uuid
        not null
        references auth.users(id)
        on delete cascade,

    operator_name varchar(200)
        not null,

    transport_mode varchar(50)
        not null,

    transport_line varchar(200),

    old_fare numeric(10, 2),

    proposed_fare numeric(10, 2)
        not null,

    effective_date date,

    description text,

    source_url text,

    evidence_storage_path text,

    status varchar(30)
        not null
        default 'pending',

    reviewed_by uuid
        references auth.users(id)
        on delete set null,

    reviewed_at timestamptz,

    review_note text,

    created_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now(),

    constraint fare_requests_transport_mode_check
        check (
            transport_mode in (
                'bus',
                'bts',
                'mrt',
                'arl',
                'train',
                'boat',
                'other'
            )
        ),

    constraint fare_requests_old_fare_check
        check (
            old_fare is null
            or old_fare >= 0
        ),

    constraint fare_requests_proposed_fare_check
        check (
            proposed_fare >= 0
        ),

    constraint fare_requests_status_check
        check (
            status in (
                'pending',
                'approved',
                'rejected',
                'needs_more_information'
            )
        )
);

create index fare_requests_submitted_by_idx
on public.fare_change_requests (submitted_by);

create index fare_requests_status_created_idx
on public.fare_change_requests (
    status,
    created_at desc
);

-- UPDATED_AT FUNCTION

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

create trigger incident_reports_set_updated_at
before update on public.incident_reports
for each row
execute function public.set_updated_at();

create trigger saved_routes_set_updated_at
before update on public.saved_routes
for each row
execute function public.set_updated_at();

create trigger fare_change_requests_set_updated_at
before update on public.fare_change_requests
for each row
execute function public.set_updated_at();

-- CREATE PROFILE AFTER SIGN-UP

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (
        id,
        display_name
    )
    values (
        new.id,
        coalesce(
            new.raw_user_meta_data ->> 'display_name',
            split_part(new.email, '@', 1),
            'Urban Flow User'
        )
    );

    return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

-- INITIAL REPORT CATEGORIES

insert into public.report_categories (
    code,
    name_th,
    name_en,
    default_expiry_minutes
)
values
    (
        'accident',
        'อุบัติเหตุ',
        'Accident',
        120
    ),
    (
        'traffic',
        'การจราจรติดขัด',
        'Heavy traffic',
        60
    ),
    (
        'flood',
        'น้ำท่วม',
        'Flood',
        360
    ),
    (
        'service_delay',
        'บริการล่าช้า',
        'Service delay',
        60
    ),
    (
        'station_closed',
        'สถานีปิด',
        'Station closed',
        720
    ),
    (
        'vehicle_breakdown',
        'รถหรือขบวนขัดข้อง',
        'Vehicle breakdown',
        120
    ),
    (
        'other',
        'อื่น ๆ',
        'Other',
        60
    );

-- ENABLE ROW LEVEL SECURITY

alter table public.profiles
enable row level security;

alter table public.report_categories
enable row level security;

alter table public.incident_reports
enable row level security;

alter table public.report_votes
enable row level security;

alter table public.saved_routes
enable row level security;

alter table public.fare_change_requests
enable row level security;

-- CREATE POLICIES For edit own profile

create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using (
    (select auth.uid()) = id
);

create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using (
    (select auth.uid()) = id
)
with check (
    (select auth.uid()) = id
);

-- CREATE POLICIES For view report categories and incident reports

create policy "report_categories_public_read"
on public.report_categories
for select
to anon, authenticated
using (
    is_active = true
);

create policy "incident_reports_public_read_verified"
on public.incident_reports
for select
to anon, authenticated
using (
    status = 'verified'
    and (
        expires_at is null
        or expires_at > now()
    )
);

create policy "incident_reports_owner_read"
on public.incident_reports
for select
to authenticated
using (
    (select auth.uid()) = reported_by
);

create policy "incident_reports_authenticated_insert"
on public.incident_reports
for insert
to authenticated
with check (
    (select auth.uid()) = reported_by
    and status = 'pending'
);

create policy "incident_reports_owner_update_pending"
on public.incident_reports
for update
to authenticated
using (
    (select auth.uid()) = reported_by
    and status = 'pending'
)
with check (
    (select auth.uid()) = reported_by
    and status = 'pending'
);

create policy "incident_reports_owner_delete_pending"
on public.incident_reports
for delete
to authenticated
using (
    (select auth.uid()) = reported_by
    and status = 'pending'
);

-- CREATE POLICIES For votes

create policy "report_votes_read_own"
on public.report_votes
for select
to authenticated
using (
    (select auth.uid()) = user_id
);

create policy "report_votes_insert_own"
on public.report_votes
for insert
to authenticated
with check (
    (select auth.uid()) = user_id
);

create policy "report_votes_update_own"
on public.report_votes
for update
to authenticated
using (
    (select auth.uid()) = user_id
)
with check (
    (select auth.uid()) = user_id
);

create policy "report_votes_delete_own"
on public.report_votes
for delete
to authenticated
using (
    (select auth.uid()) = user_id
);

-- CREATE POLICIES For saved routes

create policy "saved_routes_owner_select"
on public.saved_routes
for select
to authenticated
using (
    (select auth.uid()) = user_id
);

create policy "saved_routes_owner_insert"
on public.saved_routes
for insert
to authenticated
with check (
    (select auth.uid()) = user_id
);

create policy "saved_routes_owner_update"
on public.saved_routes
for update
to authenticated
using (
    (select auth.uid()) = user_id
)
with check (
    (select auth.uid()) = user_id
);

create policy "saved_routes_owner_delete"
on public.saved_routes
for delete
to authenticated
using (
    (select auth.uid()) = user_id
);

-- CREATE POLICIES For fare change requests

create policy "fare_requests_owner_select"
on public.fare_change_requests
for select
to authenticated
using (
    (select auth.uid()) = submitted_by
);

create policy "fare_requests_owner_insert"
on public.fare_change_requests
for insert
to authenticated
with check (
    (select auth.uid()) = submitted_by
    and status = 'pending'
);

-- CREATE INCIDENT FUNCTION

create or replace function public.create_incident_report(
    p_category_code text,
    p_title text,
    p_description text,
    p_place_name text,
    p_latitude double precision,
    p_longitude double precision,
    p_severity text default 'medium'
)
returns uuid
language plpgsql
security invoker
set search_path = public, extensions
as $$
declare
    v_category_id smallint;
    v_report_id uuid;
    v_expiry_minutes integer;
begin
    if auth.uid() is null then
        raise exception 'Authentication required';
    end if;

    if p_latitude < -90 or p_latitude > 90 then
        raise exception 'Invalid latitude';
    end if;

    if p_longitude < -180 or p_longitude > 180 then
        raise exception 'Invalid longitude';
    end if;

    if p_severity not in (
        'low',
        'medium',
        'high',
        'critical'
    ) then
        raise exception 'Invalid severity';
    end if;

    select
        id,
        default_expiry_minutes
    into
        v_category_id,
        v_expiry_minutes
    from public.report_categories
    where code = p_category_code
      and is_active = true;

    if v_category_id is null then
        raise exception 'Invalid report category';
    end if;

    insert into public.incident_reports (
        category_id,
        reported_by,
        title,
        description,
        place_name,
        location,
        severity,
        expires_at
    )
    values (
        v_category_id,
        auth.uid(),
        trim(p_title),
        nullif(trim(p_description), ''),
        nullif(trim(p_place_name), ''),
        extensions.st_setsrid(
            extensions.st_makepoint(
                p_longitude,
                p_latitude
            ),
            4326
        )::extensions.geography,
        p_severity,
        case
            when v_expiry_minutes is null
                then null
            else
                now()
                + make_interval(
                    mins => v_expiry_minutes
                )
        end
    )
    returning id into v_report_id;

    return v_report_id;
end;
$$;